# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/dev/FDU-2026spring/CS-2026spring/Lab3-2/Lab3-2-2/Lab3-2-2/Lab3-2-2.srcs/sources_1/ip/inst_mem/inst_mem.xci
# IP: The module: 'inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dev/FDU-2026spring/CS-2026spring/Lab3-2/Lab3-2-2/Lab3-2-2/Lab3-2-2.gen/sources_1/ip/inst_mem/inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/dev/FDU-2026spring/CS-2026spring/Lab3-2/Lab3-2-2/Lab3-2-2/Lab3-2-2.srcs/sources_1/ip/inst_mem/inst_mem.xci
# IP: The module: 'inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dev/FDU-2026spring/CS-2026spring/Lab3-2/Lab3-2-2/Lab3-2-2/Lab3-2-2.gen/sources_1/ip/inst_mem/inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
