# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/dev/FDU-2026spring/CS-2026spring/Lab3-1/Lab3-1-1/Lab3-1-1/Lab3-1-1.srcs/sources_1/ip/Ins_Rom/Ins_Rom.xci
# IP: The module: 'Ins_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dev/FDU-2026spring/CS-2026spring/Lab3-1/Lab3-1-1/Lab3-1-1/Lab3-1-1.gen/sources_1/ip/Ins_Rom/Ins_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ins_Rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/dev/FDU-2026spring/CS-2026spring/Lab3-1/Lab3-1-1/Lab3-1-1/Lab3-1-1.srcs/sources_1/ip/Ins_Rom/Ins_Rom.xci
# IP: The module: 'Ins_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/dev/FDU-2026spring/CS-2026spring/Lab3-1/Lab3-1-1/Lab3-1-1/Lab3-1-1.gen/sources_1/ip/Ins_Rom/Ins_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ins_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
