webtalk_init -webtalk_dir D:/dev/FDU-2026spring/CS-2026spring/24300120183_陈一璟_lab1-1/ALU_4bit/ALU_4bit.sim/sim_1/behav/xsim/xsim.dir/test_add_sub_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 20 18:43:54 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "56724971-ed8a-4f21-a01b-a34589c3a9cb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0d7e76587d76487cb4fed86bf01296cf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "39" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i9-13905H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8640_KB" -context "xsim\\usage"
webtalk_transmit -clientid 687274013 -regid "" -xml D:/dev/FDU-2026spring/CS-2026spring/24300120183_陈一璟_lab1-1/ALU_4bit/ALU_4bit.sim/sim_1/behav/xsim/xsim.dir/test_add_sub_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/dev/FDU-2026spring/CS-2026spring/24300120183_陈一璟_lab1-1/ALU_4bit/ALU_4bit.sim/sim_1/behav/xsim/xsim.dir/test_add_sub_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/dev/FDU-2026spring/CS-2026spring/24300120183_陈一璟_lab1-1/ALU_4bit/ALU_4bit.sim/sim_1/behav/xsim/xsim.dir/test_add_sub_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
